### PR TITLE
MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.01

### PR DESCRIPTION
**Pull request by halldc**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by halldc** [comment]
@bgruening @jdblischak @marcelotrevisani 
Do I need to increment the build number when I am simply re-rendering the feedstock? (to get the latest version of R)

**Comment by cbrueffer** [comment]
@halldc yes, otherwise only the R 3.5 package (but not the R3.4 one) will be uploaded which could lead to inconsistencies.

**Comment by marcelotrevisani** [comment]
If you are not changing the recipe to a new version, please always increment the build number to avoid problem.  :)

if you change the version you have to reset the build number to 0

**Comment by halldc** [comment]
@marcelotrevisani - thanks! I just wasn't sure because the recipe itself was unchanged. I couldn't find this situation described in the docs.

**Pull request merged**
